SET search_path = book_rating, public;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- TRUNCATE TABLE book RESTART IDENTITY CASCADE;

INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (1,5,'Excellent book!',false,1,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (2,3,'Interesting read.',true,1,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (3,4,'Enjoyed the story.',false,1,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (4,2,'Not my favorite.',false,1,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (5,1,'Could not finish.',true,1,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (6,5,'Highly recommended.',false,1,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (7,4,'Great for kids.',false,1,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (8,3,'Average.',true,1,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (9,2,'Too slow.',false,1,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (10,5,'Loved it!',false,1,10,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (11,3,'Not bad.',true,2,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (12,4,'Really enjoyed this one.',false,2,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (13,2,'It was okay.',false,2,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (14,1,'Didn''t like it.',true,2,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (15,5,'Outstanding!',false,2,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (16,4,'Very entertaining.',false,2,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (17,3,'Decent read.',true,2,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (18,2,'Not great.',false,2,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (19,1,'Hated it.',true,2,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (20,5,'A fantastic journey!',false,2,10,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (21,4,'Loved the characters.',false,3,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (22,3,'It was fine.',true,3,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (23,2,'Could be better.',false,3,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (24,1,'Not my cup of tea.',true,3,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (25,5,'Masterpiece!',false,3,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (26,4,'So engaging.',false,3,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (27,3,'Average storyline.',true,3,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (28,2,'Didn''t enjoy it.',false,3,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (29,1,'Boring.',true,3,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (30,5,'A thrilling read!',false,3,10,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (31,4,'Intriguing plot.',false,4,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (32,3,'Not bad, not great.',true,4,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (33,2,'A bit predictable.',false,4,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (34,1,'Didn''t like the ending.',true,4,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (35,5,'Absolutely loved it!',false,4,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (36,4,'Well written.',false,4,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (37,3,'It was okay.',true,4,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (38,2,'Not engaging.',false,4,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (39,1,'Hated the characters.',true,4,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (40,5,'A delightful surprise!',false,4,10,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (41,4,'Such depth!',false,5,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (42,3,'It was fine.',true,5,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (43,2,'Couldn''t relate.',false,5,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (44,1,'Not my type.',true,5,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (45,5,'A masterpiece!',false,5,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (46,4,'Very enjoyable.',false,5,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (47,3,'Average read.',true,5,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (48,2,'Too lengthy.',false,5,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (49,1,'Didn''t enjoy it.',true,5,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (50,5,'An emotional journey.',false,5,10,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (51,4,'Remarkable characters.',false,6,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (52,3,'It had its moments.',true,6,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (53,2,'Not engaging enough.',false,6,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (54,1,'Boring and predictable.',true,6,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (55,5,'A true classic!',false,6,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (56,4,'So much depth.',false,6,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (57,3,'Decent enough.',true,6,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (58,2,'The plot didn''t work for me.',false,6,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (59,1,'Didn''t connect with the story.',true,6,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (60,5,'A gripping tale!',false,6,10,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (61,4,'Loved the writing style.',false,7,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (62,3,'It was okay, I guess.',true,7,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (63,2,'Not my favorite genre.',false,7,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (64,1,'Couldn''t get into it.',true,7,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (65,5,'Masterfully crafted.',false,7,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (66,4,'Such an important story.',false,7,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (67,3,'Average at best.',true,7,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (68,2,'Too predictable.',false,7,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (69,1,'A complete bore.',true,7,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (70,5,'An instant classic!',false,7,10,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (71,4,'Such an emotional read.',false,8,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (72,3,'It had potential.',true,8,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (73,2,'Not my cup of tea.',false,8,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (74,1,'Didn''t like the characters.',true,8,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (75,5,'A breathtaking journey.',false,8,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (76,4,'Incredible depth and detail.',false,8,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (77,3,'Decent read.',true,8,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (78,2,'The story was lacking.',false,8,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (79,1,'Not my type of book.',true,8,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (80,5,'A delightful surprise.',false,8,10,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (81,4,'Such a profound book.',false,9,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (82,3,'It was okay, I guess.',true,9,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (83,2,'Not great.',false,9,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (84,1,'Didn''t like the ending.',true,9,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (85,5,'Absolutely loved it!',false,9,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (86,4,'Well written.',false,9,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (87,3,'It was okay.',true,9,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (88,2,'Not engaging.',false,9,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (89,1,'Hated the characters.',true,9,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (90,5,'A gripping tale!',false,9,10,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (91,4,'Loved the writing style.',false,10,1,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (92,3,'It was okay, I guess.',true,10,2,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (93,2,'Not my favorite genre.',false,10,3,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (94,1,'Couldn''t get into it.',true,10,4,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (95,5,'Masterfully crafted.',false,10,5,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (96,4,'Such an important story.',false,10,6,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (97,3,'Average at best.',true,10,7,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (98,2,'Too predictable.',false,10,8,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (99,1,'A complete bore.',true,10,9,0,'seed',now());
INSERT INTO rating (id,score,description,archived,user_id,book_id,rec_version,created_by,created_ts) VALUES (100,5,'An instant classic!',false,10,10,0,'seed',now());

SELECT setval('rating_seq', (SELECT max(id) FROM rating));