server:
    port: 9000

spring:
  application:
    name: book-rating
  datasource:
    url: jdbc:postgresql://localhost:5432/book-service-db
    username: book_app
    password: app123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: book_rating
  security:
    user:
      name: admin
      password: admin123



logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG


app:
  security:
    jwt:
      issuer: "book-rating-service"
      access-ttl: PT15M
      refresh-ttl: P14D
      private-pem-path: jwt-private.pem
  rating:
    bayes:
      m: 50
