DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${ADMIN_USER}') THEN
        CREATE ROLE ${ADMIN_USER}
        LOGIN
        PASSWORD '${ADMIN_PASSWORD}'
        NOSUPERUSER
        CREATEDB
        CREATEROLE
        INHERIT;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${APP_USER}') THEN
        CREATE ROLE ${APP_USER}
        LOGIN
        PASSWORD '${APP_PASSWORD}'
        NOSUPERUSER
        NOCREATEDB
        NOCREATEROLE
        INHERIT;
    END IF;
END$$;

CREATE SCHEMA IF NOT EXISTS ${SCHEMA} AUTHORIZATION ${ADMIN_USER};

GRANT USAGE, CREATE ON SCHEMA ${SCHEMA} TO ${ADMIN_USER};

GRANT USAGE ON SCHEMA ${SCHEMA} TO ${APP_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA}
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${APP_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA}
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${APP_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ${SCHEMA} TO ${APP_USER};
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA ${SCHEMA} TO ${APP_USER};

ALTER ROLE ${APP_USER} SET search_path TO ${SCHEMA}, public;